apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fileupdatestest-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/fileupdatestest/fileupdatestest-component@sha256:bcf7c9ebf6de508577cc32b7f41bb2a73549aaffdbf6fe27ca3da9562c391725
        name: my-python
        resources: {}
status: {}
